apiDir: "../rain-rest-api/src/main/java"
apiPackagePath: "com.liferay.rain.rest"
application:
    baseURI: "/rain-rest"
    className: "RainRestApplication"
    name: "RainRest"
author: "me"
clientDir: "../rain-rest-client/src/main/java"
testDir: "../rain-rest-test/src/testIntegration/java"