/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.rain.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Doctor service. Represents a row in the &quot;Rain_Doctor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.rain.service.model.impl.DoctorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.rain.service.model.impl.DoctorImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Doctor
 * @generated
 */
@ProviderType
public interface DoctorModel extends BaseModel<Doctor> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doctor model instance should use the {@link Doctor} interface instead.
	 */

	/**
	 * Returns the primary key of this doctor.
	 *
	 * @return the primary key of this doctor
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doctor.
	 *
	 * @param primaryKey the primary key of this doctor
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the employee ID of this doctor.
	 *
	 * @return the employee ID of this doctor
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this doctor.
	 *
	 * @param employeeId the employee ID of this doctor
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this doctor.
	 *
	 * @return the group ID of this doctor
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this doctor.
	 *
	 * @param groupId the group ID of this doctor
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the surname of this doctor.
	 *
	 * @return the surname of this doctor
	 */
	@AutoEscape
	public String getSurname();

	/**
	 * Sets the surname of this doctor.
	 *
	 * @param surname the surname of this doctor
	 */
	public void setSurname(String surname);

	/**
	 * Returns the first name of this doctor.
	 *
	 * @return the first name of this doctor
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this doctor.
	 *
	 * @param firstName the first name of this doctor
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the department of this doctor.
	 *
	 * @return the department of this doctor
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this doctor.
	 *
	 * @param department the department of this doctor
	 */
	public void setDepartment(String department);

	/**
	 * Returns the govt ID of this doctor.
	 *
	 * @return the govt ID of this doctor
	 */
	@AutoEscape
	public String getGovtId();

	/**
	 * Sets the govt ID of this doctor.
	 *
	 * @param govtId the govt ID of this doctor
	 */
	public void setGovtId(String govtId);

	/**
	 * Returns the nationality of this doctor.
	 *
	 * @return the nationality of this doctor
	 */
	@AutoEscape
	public String getNationality();

	/**
	 * Sets the nationality of this doctor.
	 *
	 * @param nationality the nationality of this doctor
	 */
	public void setNationality(String nationality);

	/**
	 * Returns the pay group of this doctor.
	 *
	 * @return the pay group of this doctor
	 */
	@AutoEscape
	public String getPayGroup();

	/**
	 * Sets the pay group of this doctor.
	 *
	 * @param payGroup the pay group of this doctor
	 */
	public void setPayGroup(String payGroup);

	/**
	 * Returns the email of this doctor.
	 *
	 * @return the email of this doctor
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this doctor.
	 *
	 * @param email the email of this doctor
	 */
	public void setEmail(String email);

	/**
	 * Returns the contact number of this doctor.
	 *
	 * @return the contact number of this doctor
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this doctor.
	 *
	 * @param contactNumber the contact number of this doctor
	 */
	public void setContactNumber(String contactNumber);

	@Override
	public Doctor cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}