/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.rain.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.rain.service.model.Patient;
import com.liferay.rain.service.model.PatientModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Patient service. Represents a row in the &quot;Rain_Patient&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PatientModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PatientImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PatientImpl
 * @generated
 */
@JSON(strict = true)
public class PatientModelImpl
	extends BaseModelImpl<Patient> implements PatientModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a patient model instance should use the <code>Patient</code> interface instead.
	 */
	public static final String TABLE_NAME = "Rain_Patient";

	public static final Object[][] TABLE_COLUMNS = {
		{"govtId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"surname", Types.VARCHAR}, {"firstName", Types.VARCHAR},
		{"nationality", Types.VARCHAR}, {"age", Types.BIGINT},
		{"isAdult", Types.BOOLEAN}, {"email", Types.VARCHAR},
		{"contactNumber", Types.VARCHAR}, {"insuranceId", Types.VARCHAR},
		{"primaryDoctor", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("govtId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("surname", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nationality", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("age", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("isAdult", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactNumber", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("insuranceId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("primaryDoctor", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Rain_Patient (govtId LONG not null primary key,groupId LONG,surname VARCHAR(75) null,firstName VARCHAR(75) null,nationality VARCHAR(75) null,age LONG,isAdult BOOLEAN,email VARCHAR(75) null,contactNumber VARCHAR(75) null,insuranceId VARCHAR(75) null,primaryDoctor LONG)";

	public static final String TABLE_SQL_DROP = "drop table Rain_Patient";

	public static final String ORDER_BY_JPQL = " ORDER BY patient.surname ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Rain_Patient.surname ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AGE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTACTNUMBER_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMAIL_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GOVTID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long INSURANCEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NATIONALITY_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long PRIMARYDOCTOR_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SURNAME_COLUMN_BITMASK = 128L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PatientModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _govtId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setGovtId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _govtId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Patient.class;
	}

	@Override
	public String getModelClassName() {
		return Patient.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Patient, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Patient, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Patient)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Patient, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Patient, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Patient)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Patient, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Patient, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Patient, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Patient, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Patient, Object>>();
		Map<String, BiConsumer<Patient, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Patient, ?>>();

		attributeGetterFunctions.put("govtId", Patient::getGovtId);
		attributeSetterBiConsumers.put(
			"govtId", (BiConsumer<Patient, Long>)Patient::setGovtId);
		attributeGetterFunctions.put("groupId", Patient::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Patient, Long>)Patient::setGroupId);
		attributeGetterFunctions.put("surname", Patient::getSurname);
		attributeSetterBiConsumers.put(
			"surname", (BiConsumer<Patient, String>)Patient::setSurname);
		attributeGetterFunctions.put("firstName", Patient::getFirstName);
		attributeSetterBiConsumers.put(
			"firstName", (BiConsumer<Patient, String>)Patient::setFirstName);
		attributeGetterFunctions.put("nationality", Patient::getNationality);
		attributeSetterBiConsumers.put(
			"nationality",
			(BiConsumer<Patient, String>)Patient::setNationality);
		attributeGetterFunctions.put("age", Patient::getAge);
		attributeSetterBiConsumers.put(
			"age", (BiConsumer<Patient, Long>)Patient::setAge);
		attributeGetterFunctions.put("isAdult", Patient::getIsAdult);
		attributeSetterBiConsumers.put(
			"isAdult", (BiConsumer<Patient, Boolean>)Patient::setIsAdult);
		attributeGetterFunctions.put("email", Patient::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Patient, String>)Patient::setEmail);
		attributeGetterFunctions.put(
			"contactNumber", Patient::getContactNumber);
		attributeSetterBiConsumers.put(
			"contactNumber",
			(BiConsumer<Patient, String>)Patient::setContactNumber);
		attributeGetterFunctions.put("insuranceId", Patient::getInsuranceId);
		attributeSetterBiConsumers.put(
			"insuranceId",
			(BiConsumer<Patient, String>)Patient::setInsuranceId);
		attributeGetterFunctions.put(
			"primaryDoctor", Patient::getPrimaryDoctor);
		attributeSetterBiConsumers.put(
			"primaryDoctor",
			(BiConsumer<Patient, Long>)Patient::setPrimaryDoctor);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getGovtId() {
		return _govtId;
	}

	@Override
	public void setGovtId(long govtId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_govtId = govtId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGovtId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("govtId"));
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	@JSON
	@Override
	public String getSurname() {
		if (_surname == null) {
			return "";
		}
		else {
			return _surname;
		}
	}

	@Override
	public void setSurname(String surname) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_surname = surname;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSurname() {
		return getColumnOriginalValue("surname");
	}

	@JSON
	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@JSON
	@Override
	public String getNationality() {
		if (_nationality == null) {
			return "";
		}
		else {
			return _nationality;
		}
	}

	@Override
	public void setNationality(String nationality) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nationality = nationality;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalNationality() {
		return getColumnOriginalValue("nationality");
	}

	@JSON
	@Override
	public long getAge() {
		return _age;
	}

	@Override
	public void setAge(long age) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_age = age;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalAge() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("age"));
	}

	@JSON
	@Override
	public boolean getIsAdult() {
		return _isAdult;
	}

	@JSON
	@Override
	public boolean isIsAdult() {
		return _isAdult;
	}

	@Override
	public void setIsAdult(boolean isAdult) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isAdult = isAdult;
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalEmail() {
		return getColumnOriginalValue("email");
	}

	@JSON
	@Override
	public String getContactNumber() {
		if (_contactNumber == null) {
			return "";
		}
		else {
			return _contactNumber;
		}
	}

	@Override
	public void setContactNumber(String contactNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contactNumber = contactNumber;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalContactNumber() {
		return getColumnOriginalValue("contactNumber");
	}

	@JSON
	@Override
	public String getInsuranceId() {
		if (_insuranceId == null) {
			return "";
		}
		else {
			return _insuranceId;
		}
	}

	@Override
	public void setInsuranceId(String insuranceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_insuranceId = insuranceId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalInsuranceId() {
		return getColumnOriginalValue("insuranceId");
	}

	@JSON
	@Override
	public long getPrimaryDoctor() {
		return _primaryDoctor;
	}

	@Override
	public void setPrimaryDoctor(long primaryDoctor) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_primaryDoctor = primaryDoctor;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalPrimaryDoctor() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("primaryDoctor"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Patient.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Patient toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Patient>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PatientImpl patientImpl = new PatientImpl();

		patientImpl.setGovtId(getGovtId());
		patientImpl.setGroupId(getGroupId());
		patientImpl.setSurname(getSurname());
		patientImpl.setFirstName(getFirstName());
		patientImpl.setNationality(getNationality());
		patientImpl.setAge(getAge());
		patientImpl.setIsAdult(isIsAdult());
		patientImpl.setEmail(getEmail());
		patientImpl.setContactNumber(getContactNumber());
		patientImpl.setInsuranceId(getInsuranceId());
		patientImpl.setPrimaryDoctor(getPrimaryDoctor());

		patientImpl.resetOriginalValues();

		return patientImpl;
	}

	@Override
	public Patient cloneWithOriginalValues() {
		PatientImpl patientImpl = new PatientImpl();

		patientImpl.setGovtId(this.<Long>getColumnOriginalValue("govtId"));
		patientImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		patientImpl.setSurname(this.<String>getColumnOriginalValue("surname"));
		patientImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		patientImpl.setNationality(
			this.<String>getColumnOriginalValue("nationality"));
		patientImpl.setAge(this.<Long>getColumnOriginalValue("age"));
		patientImpl.setIsAdult(this.<Boolean>getColumnOriginalValue("isAdult"));
		patientImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		patientImpl.setContactNumber(
			this.<String>getColumnOriginalValue("contactNumber"));
		patientImpl.setInsuranceId(
			this.<String>getColumnOriginalValue("insuranceId"));
		patientImpl.setPrimaryDoctor(
			this.<Long>getColumnOriginalValue("primaryDoctor"));

		return patientImpl;
	}

	@Override
	public int compareTo(Patient patient) {
		int value = 0;

		value = getSurname().compareTo(patient.getSurname());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Patient)) {
			return false;
		}

		Patient patient = (Patient)object;

		long primaryKey = patient.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Patient> toCacheModel() {
		PatientCacheModel patientCacheModel = new PatientCacheModel();

		patientCacheModel.govtId = getGovtId();

		patientCacheModel.groupId = getGroupId();

		patientCacheModel.surname = getSurname();

		String surname = patientCacheModel.surname;

		if ((surname != null) && (surname.length() == 0)) {
			patientCacheModel.surname = null;
		}

		patientCacheModel.firstName = getFirstName();

		String firstName = patientCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			patientCacheModel.firstName = null;
		}

		patientCacheModel.nationality = getNationality();

		String nationality = patientCacheModel.nationality;

		if ((nationality != null) && (nationality.length() == 0)) {
			patientCacheModel.nationality = null;
		}

		patientCacheModel.age = getAge();

		patientCacheModel.isAdult = isIsAdult();

		patientCacheModel.email = getEmail();

		String email = patientCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			patientCacheModel.email = null;
		}

		patientCacheModel.contactNumber = getContactNumber();

		String contactNumber = patientCacheModel.contactNumber;

		if ((contactNumber != null) && (contactNumber.length() == 0)) {
			patientCacheModel.contactNumber = null;
		}

		patientCacheModel.insuranceId = getInsuranceId();

		String insuranceId = patientCacheModel.insuranceId;

		if ((insuranceId != null) && (insuranceId.length() == 0)) {
			patientCacheModel.insuranceId = null;
		}

		patientCacheModel.primaryDoctor = getPrimaryDoctor();

		return patientCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Patient, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Patient, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Patient, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Patient)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Patient>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Patient.class, ModelWrapper.class);

	}

	private long _govtId;
	private long _groupId;
	private String _surname;
	private String _firstName;
	private String _nationality;
	private long _age;
	private boolean _isAdult;
	private String _email;
	private String _contactNumber;
	private String _insuranceId;
	private long _primaryDoctor;

	public <T> T getColumnValue(String columnName) {
		Function<Patient, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Patient)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("govtId", _govtId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("surname", _surname);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("nationality", _nationality);
		_columnOriginalValues.put("age", _age);
		_columnOriginalValues.put("isAdult", _isAdult);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("contactNumber", _contactNumber);
		_columnOriginalValues.put("insuranceId", _insuranceId);
		_columnOriginalValues.put("primaryDoctor", _primaryDoctor);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("govtId", 1L);

		columnBitmasks.put("groupId", 2L);

		columnBitmasks.put("surname", 4L);

		columnBitmasks.put("firstName", 8L);

		columnBitmasks.put("nationality", 16L);

		columnBitmasks.put("age", 32L);

		columnBitmasks.put("isAdult", 64L);

		columnBitmasks.put("email", 128L);

		columnBitmasks.put("contactNumber", 256L);

		columnBitmasks.put("insuranceId", 512L);

		columnBitmasks.put("primaryDoctor", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Patient _escapedModel;

}